# Generated by Django 5.1.6 on 2025-02-16 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='typingattempt',
            old_name='Timestamp',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='typingattempt',
            name='user',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
