# Generated by Django 5.1.6 on 2025-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingtest', '0002_rename_timestamp_typingattempt_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='start_time',
            field=models.DateTimeField(default='3000-02-15 12:00:00'),
        ),
    ]
